pipeline:
  build:
    image: maven:3-jdk-10
    commands:
      - echo "Compiling the code..."
      - mvn clean package
  test:
    image: maven:3-jdk-10
    commands:
      - echo "Running tests"
      - java -cp target/helloworld-1.1.jar com.coveros.demo.helloworld.HelloWorld
