kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64


steps:
- name: backend
  image: maven:3-jdk-10
  commands:
    - echo "Compiling the code..."
    - mvn clean package

- name: ea_test
  image: maven:3-jdk-10
  commands:
    - echo "Running tests"
    - java -cp target/helloworld-1.1.jar com.coveros.demo.helloworld.HelloWorld
